server:
  port: 8080
  address: 127.0.0.1

spring:
  datasource:
    url: jdbc:mysql://134.175.126.96:3306/sdes?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: )OKM!qaz
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 134.175.126.96
      port: 6379

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

minio:
  endpoint: http://134.175.126.96:9000
  bucket: public-readonly-file
  accesskey: admin
  secretkey: admin@123
  expiry: 1 # redis 文件信息失效时间 天
  breakpointTime: 1 # 分片地址失效时间 天


mqtt:
  enabled: true
  server:
    uri: tcp://broker.emqx.io:1883
  client:
    id: spring-minio-release-erictang
  username: admin
  password: public